  List<String> captionKeywords = [
    'flutter',
    'programming',
    'coding',
    'technology',
    'cloud',
    'computing',
    'artificial intelligence',
    'machine learning',
    'go lang',
    'dart',
    'competitive programming',
    'contest',
    'google',
    'amazon',
    'facebook',
    'netflix',
    'c++',
    'c',
    'javascript',
    'react',
    'reactjs',
    'angular',
    'angularjs',
    'nodejs',
    'bootstrap',
    'android',
    'tailwindcss',
    'twitter',
    'github',
    'codeblocks',
    'django',
    'mongodb',
    'html',
    'css',
    'kotlin',
    'python',
    'java',
    'dotnet',
    'networking',
    'computer networks',
    

  ];